# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Awesome-List' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Awesome-List
  pod 'RxSwift', '~> 3.6'
  pod 'RxAlamofire', '~> 3.0'
  pod 'IGListKit', '~> 3.0'

end
